### ISSUE TITLE
Allow mapping of verbs to backend verbs

### ISSUE THREAD

**Issue by daniel-garcia** [infobloxopen/seal#13]
Seal lets you define a set of verbs for types but the backends may support OTHER verbs. This task is to allow the customization of backend policies to follow a given mapping.

**Comment by wplu** [comment]
DEMO - customizable verbs, i.e. `inspect`, `read`, `use`, `manage`:
https://github.com/infobloxopen/seal/blob/master/docs/source/examples/simple/products.inventory.swagger
```
openapi: "3.0.0"
components:
  schemas:
    allow:
      type: object
      properties:
        log:
          type: boolean
      x-seal-type: action
    products.inventory:
      type: object
      x-seal-actions:
      - allow
      - deny
      x-seal-verbs:
      - inspect
      - read
      - use
      - manage
      x-seal-default-action: deny
© 2020 G
```
