### ISSUE TITLE
allow tags as a type property in custom swagger types

### ISSUE THREAD

**Issue by wplu** [infobloxopen/seal#39]
Use standard openapiv3 attributes for `tag`...  See component object: https://swagger.io/specification/

Please change petstore.all.seal to:
```
deny subject group everyone to buy petstore.pet where ctx.tag["endangered"] == "true";
```

It should look like `petstore.pet` swagger file:
```
openapi: "3.0.0"
components:
  schemas:
    petstore.pet:
      type: object
      properties:
...
        tags:
          type: array
          items:
            $ref: "#/components/schemas/tag"
...
```

global swagger file defines `tag` type - see #76:
```
openapi: "3.0.0"
components:
  schemas:
    tag:
      type: object
      additionalProperties: true
```

references:
see https://github.com/infobloxopen/seal/pull/25

rego:
```
deny {
...
    input.tags["endangered"] == "true"
}
```

**Comment by abynenkov-ib** [comment]
`$ref: '#/components/schemas/tag'` seems to be ok only in case `tag` is defined at the same swagger file
