### ISSUE TITLE
ctx should support objects with multiple hierarchy

### ISSUE THREAD

**Issue by wplu** [infobloxopen/seal#83]
@daniel-garcia wanted to support object hierarchies, so wanted ctx to support array of multiple objects.

_Originally posted by @rchowinfoblox in https://github.com/infobloxopen/seal/issues/81#issuecomment-713290629_

**Comment by wplu** [comment]
@daniel-garcia @rchowinfoblox :
What does swagger types and ctx look like for objects with multiple hierarchies?

**Comment by rchowinfoblox** [comment]
See AuthZ HLD https://docs.google.com/document/d/1pgEBYnD2iyozLc4fW6qt95zkMSQ525Mchvqpg7g6KWY/edit#heading=h.44u3hmx8v4p3

rego should look like:
`
allow {
  data.authz.jwtclaims.seal_subject.account_id == "40"
  data.authz.jwtclaims.seal_subject.groups[_] == "admin"
  input.resource_type == "ddi.subnet"
  input.verb == "manage"
  input.ctx[i].id == "guid1"
  input.ctx[i].tags.zone == "apj"
}
`

**Comment by wplu** [comment]
this is not correct:
```
  data.authz.jwtclaims.seal_subject.tenant_ref == "SD_ZOO"
```

if the policy had:
```
context {
    where subject.tenant_ref == "SD_ZOO";
} ... {
}
```

then the rego for that would be:
```
...
    seal_subject.tenant_ref == "SD_ZOO"
...
```

**Comment by wplu** [comment]
this is not correct either:
```
  data.authz.jwtclaims.seal_subject.groups[_] == "managers"
```

**Comment by wplu** [comment]
@rchowinfoblox will use `input.type` instead of `input.resource_type`
