### ISSUE TITLE
Support non-standard JWT claims

### ISSUE THREAD

**Issue by rchowinfoblox** [infobloxopen/seal#94]
Support non-standard JWT claims, in particular Infoblox JWT claims.

Example of Infoblox JWT claims:
```
{
}
```

**Comment by rchowinfoblox** [comment]
@daniel-garcia @wplu pls comment whether this needs to be supported.

**Comment by wplu** [comment]
non-standard JWT claims will be supported by creating a swagger type similar to petstore.jwt.swagger in the appropriate repo that is not here in the seal repo.  When the compiler is instantiated, pass that swagger instead of petstore.jwt.swagger.
